version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "installing packages"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "running tests"
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test
